server:
  port: 8087
# 应用名称
spring:
  application:
    name: token

eureka:
  instance:
    #显示IP地址
    prefer-ip-address: true
    #默认值为：机器名称：服务名称：实例得端口
    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:8081/eureka/eureka


